name: Django AKS Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Hub Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t shivam20012004/django-app:${{ github.sha }} .
        docker push shivam20012004/django-app:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.AKS_CLUSTER }}

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/django-app \
          django-app=shivam20012004/django-app:${{ github.sha }}

    - name: Wait for Rollout
      run: |
        kubectl rollout status deployment/django-app

    - name: Get External IP
      run: |
        echo "=========================================="
        echo "🚀 Application is Live at:"
        kubectl get service django-service --output jsonpath='{.status.loadBalancer.ingress[0].ip}'
        echo ""
        echo "=========================================="